apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource
spec:
  selector:
    matchLabels:
      app: resource
  template:
    metadata:
      labels:
        app: resource
    spec:
      containers:
      - name: resource
        image: resource-image
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: http
          containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: resource
spec:
  selector:
    app: resource
  ports:
  - name: http
    port: 3000
    targetPort: http

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: resource
  labels:
    name: resource
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "http://auth.default.svc.cluster.local:3000/"
    nginx.ingress.kubernetes.io/auth-response-headers: "X-Auth-Attributes"
spec:
  ingressClassName: nginx
  rules:
  - host: localhost
    http:
      paths:
      - pathType: Prefix
        path: "/resource"
        backend:
          service:
            name: resource
            port:
              name: http
